"use strict";

// Generated by CoffeeScript 2.7.0
(function () {
  // Everything is an expression -> all return except (break, continue and return)
  var eldest, globals, grade, name, one, six, three, two;

  grade = function grade(student) {
    if (student.excellentWork) {
      return "A+";
    } else if (student.okayStuff) {
      if (student.triedHard) {
        return "B";
      } else {
        return "B-";
      }
    } else {
      return "C";
    }
  };

  eldest = 24 > 21 ? "Liz" : "Ike";
  console.log(grade, eldest);
  six = (one = 1) + (two = 2) + (three = 3); //# the declaration of variables automaticaly is in the top

  console.log(six);

  globals = function () {
    var results;
    results = [];

    for (name in window) {
      results.push(name);
    }

    return results;
  }().slice(0, 10);

  console.log(globals); //alert(
  //  try
  //    nonexistent / undefined
  //  catch error
  //    "And the error is ... #{error}"
  //)
}).call(void 0);
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJtYXBwaW5ncyI6Ijs7O0FBQWdGO0VBQUE7RUFBQTs7RUFDOUVBLFFBQVEsZUFBQ0MsT0FBRDtJQUNQLElBQUdBLE9BQU8sQ0FBQ0MsYUFBWDthQUNFO0lBREYsT0FFSyxJQUFHRCxPQUFPLENBQUNFLFNBQVg7TUFDSCxJQUFHRixPQUFPLENBQUNHLFNBQVg7ZUFBMEI7TUFBMUI7ZUFBbUM7TUFEaEM7SUFBQTthQUdIOztFQU5LLENBQVI7O0VBT0FDLFNBQVksS0FBSyxFQUFMLEdBQWEsS0FBYixHQUF3QixLQUFwQztFQUVBQyxPQUFPLENBQUNDLEdBQVIsQ0FBWVAsS0FBWixFQUFtQkssTUFBbkI7RUFFQUcsTUFBTSxDQUFDQyxNQUFNLENBQVAsS0FBYUMsTUFBTSxDQUFuQixLQUF5QkMsUUFBUSxDQUFqQyxDQUFOLENBWjhFOztFQWE5RUwsT0FBTyxDQUFDQyxHQUFSLENBQVlDLEdBQVo7O0VBRUFJLFVBQVU7O0lBQUNDOztJQUFBO21CQUFBQztJQUFBOzs7R0FBRCxHQUF5QkMsS0FBekIsQ0FBeUIsQ0FBekIsRUFBeUIsRUFBekIsQ0FBVjs7RUFFQVQsT0FBTyxDQUFDQyxHQUFSLENBQVlLLE9BQVosRUFqQjhFOzs7Ozs7Q0FBQSIsIm5hbWVzIjpbImdyYWRlIiwic3R1ZGVudCIsImV4Y2VsbGVudFdvcmsiLCJva2F5U3R1ZmYiLCJ0cmllZEhhcmQiLCJlbGRlc3QiLCJjb25zb2xlIiwibG9nIiwic2l4Iiwib25lIiwidHdvIiwidGhyZWUiLCJnbG9iYWxzIiwicmVzdWx0cyIsIm5hbWUiLCJzbGljZSJdLCJzb3VyY2VSb290IjoiLi4vIiwic291cmNlcyI6WyJzcmMvbWFpbi5jb2ZmZWUiXSwic291cmNlc0NvbnRlbnQiOlsiICMgRXZlcnl0aGluZyBpcyBhbiBleHByZXNzaW9uIC0+IGFsbCByZXR1cm4gZXhjZXB0IChicmVhaywgY29udGludWUgYW5kIHJldHVybilcclxuZ3JhZGUgPSAoc3R1ZGVudCkgLT5cclxuICBpZiBzdHVkZW50LmV4Y2VsbGVudFdvcmtcclxuICAgIFwiQStcIlxyXG4gIGVsc2UgaWYgc3R1ZGVudC5va2F5U3R1ZmZcclxuICAgIGlmIHN0dWRlbnQudHJpZWRIYXJkIHRoZW4gXCJCXCIgZWxzZSBcIkItXCJcclxuICBlbHNlXHJcbiAgICBcIkNcIlxyXG5lbGRlc3QgPSBpZiAyNCA+IDIxIHRoZW4gXCJMaXpcIiBlbHNlIFwiSWtlXCJcclxuXHJcbmNvbnNvbGUubG9nIGdyYWRlLCBlbGRlc3RcclxuXHJcbnNpeCA9IChvbmUgPSAxKSArICh0d28gPSAyKSArICh0aHJlZSA9IDMpICMjIHRoZSBkZWNsYXJhdGlvbiBvZiB2YXJpYWJsZXMgYXV0b21hdGljYWx5IGlzIGluIHRoZSB0b3BcclxuY29uc29sZS5sb2cgc2l4XHJcblxyXG5nbG9iYWxzID0gKG5hbWUgZm9yIG5hbWUgb2Ygd2luZG93KVswLi4uMTBdXHJcblxyXG5jb25zb2xlLmxvZyBnbG9iYWxzXHJcblxyXG4jYWxlcnQoXHJcbiMgIHRyeVxyXG4jICAgIG5vbmV4aXN0ZW50IC8gdW5kZWZpbmVkXHJcbiMgIGNhdGNoIGVycm9yXHJcbiMgICAgXCJBbmQgdGhlIGVycm9yIGlzIC4uLiAje2Vycm9yfVwiXHJcbiMpXHJcblxyXG4iXX0=
//# sourceURL=/home/luisangel2895/courses/coffee-script/src/main.coffee